// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5eGfW_0kxs9SjGqMpDcjRCN6NCDmT4DU',
    appId: '1:1000337125532:web:59350e6102c110b6dd3d59',
    messagingSenderId: '1000337125532',
    projectId: 'bolus-connect-flutter',
    authDomain: 'bolus-connect-flutter.firebaseapp.com',
    storageBucket: 'bolus-connect-flutter.firebasestorage.app',
    measurementId: 'G-Z100NH7R6V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLWad1bqArwQQQh2jCrlXhyKb5jyueU1c',
    appId: '1:1000337125532:android:79d555d79039349add3d59',
    messagingSenderId: '1000337125532',
    projectId: 'bolus-connect-flutter',
    storageBucket: 'bolus-connect-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSqtyVCa99OTHpfVsyhbNeQELfwqNqq7w',
    appId: '1:1000337125532:ios:b44c73437c7c5c23dd3d59',
    messagingSenderId: '1000337125532',
    projectId: 'bolus-connect-flutter',
    storageBucket: 'bolus-connect-flutter.firebasestorage.app',
    iosBundleId: 'com.example.bolusConnectFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSqtyVCa99OTHpfVsyhbNeQELfwqNqq7w',
    appId: '1:1000337125532:ios:b44c73437c7c5c23dd3d59',
    messagingSenderId: '1000337125532',
    projectId: 'bolus-connect-flutter',
    storageBucket: 'bolus-connect-flutter.firebasestorage.app',
    iosBundleId: 'com.example.bolusConnectFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5eGfW_0kxs9SjGqMpDcjRCN6NCDmT4DU',
    appId: '1:1000337125532:web:9f874793ebd8b477dd3d59',
    messagingSenderId: '1000337125532',
    projectId: 'bolus-connect-flutter',
    authDomain: 'bolus-connect-flutter.firebaseapp.com',
    storageBucket: 'bolus-connect-flutter.firebasestorage.app',
    measurementId: 'G-GH4QXC394C',
  );
}
