# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "Runner.xcodeproj")
    
    # Install the provisioning profile directly
    install_provisioning_profile(path: "/Users/iangcastillo/Downloads/comcastillobolusConnectFlutter_AppStore.mobileprovision")
    
    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_options: {
        method: "app-store",
        teamID: "2946GBAHU9",
        signingStyle: "manual",
        provisioningProfiles: {
          "com.castillo.bolusConnectFlutter" => "com.castillo.bolusConnectFlutter AppStore"
        }
      }
    )
    upload_to_testflight
  end
end
